[package]
name = "gimura-preprocessor-lib"
version = "0.1.1"
edition = "2021"
description = "A small library for file peprocessing."
license = "MIT"

[dependencies]
glob = "0.3.1"
log = "0.4.22"

[dev-dependencies]
env_logger = "0.11.5"